version: '3'
services:
  application:
    container_name: tras_backend
    networks:
      - tras_network
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - tras_db
    links:
      - "tras_db:tras_db"
    restart: always
  tras_db:
    container_name: tras_db
    networks:
      - tras_network
    image: postgres
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
  tras_network:
    driver: bridge
volumes:
  postgres_data:
